### ISSUE TITLE
Slow motion

### ISSUE THREAD

**Issue by Drakey001** [sirajuddin97/CLEORelease#1]
On the armour hack, when you use it and log in-game, it justs put you into slowmotion and when you press INSERT nothing happens

**Comment by sirajuddin97** [comment]
Please read the documentation on GitHub. The kevlar hack where you use 'INSERT' is v.1, I have a new version (v.2) where you simply use /setarmour [amount].

**Comment by Drakey001** [comment]
I don't see it.
